import http.client

conn = http.client.HTTPConnection("path_to_your_api")

headers = { 'authorization': "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkZYVjE0VXE5SDFUMmh6cWxSeEVhWSJ9.eyJpc3MiOiJodHRwczovL2Rldi1lYWV6amJ6OGYybmhlaHFxLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJySTduemZGS21KeTBSWlRKSlk0bmM4YXd1cUQyTU1qa0BjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9mYXN0YXBpZXhhbXBsZS5jb20iLCJpYXQiOjE3NjEzNDk4NjksImV4cCI6MTc2MTQzNjI2OSwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIiwiYXpwIjoickk3bnpmRkttSnkwUlpUSkpZNG5jOGF3dXFEMk1NamsifQ.muVVdcxgFRlfWNvUagFRxkMHmuxjaLXwowqGL1VGe6ClwLPE5y44EGjuBXzxmUmZnYhk5j1ddc1BGTP8UqLMQEGKsGvUiu5qjwC7LPX-GgPogfR24prsuWRWRMdJAQHmPG230LG8E-vVuvocTLg2p7QoIIQTYm3WbAsXM5HKlT-LYsMeIAyacY5OD_UFAWMn1GWZEA-utMR1CKqBx9kcKWATmvxh8vEdNZdHXLA5oXoE4KQeFEhI_f0WHLOevrVRDyRAZx22IFoF8YyaEwGiihe5yhnliTFboWdrC5Wzw5gBdu-lgTceImNjuVd4c513FZP6njRnAdehISopkw2FZQ" }

conn.request("GET", "/", headers=headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))